stages:
  - test
  - build
  - review
  - deploy
  
test-app:
  stage: test
  script:
    - echo "Testing the app"
    
build-app:
  stage: build
  script:
    - echo "Building the app"
    
review-app:
  stage: review
  script:
    - echo "Reviewing the app"
    
deploy-app:
  stage: deploy
  script:
    - echo "Deploying the app"
